export const BASIC_INFO_STORE_START = 'BASIC_INFO_STORE_START';
export const BASIC_INFO_STORE_SUCCESS = 'BASIC_INFO_STORE_SUCCESS';
export const BASIC_INFO_STORE_FAIL = 'BASIC_INFO_STORE_FAIL';
export const BASIC_INFO_STORE_INIT = 'BASIC_INFO_STORE_INIT';
export const LOAD_FIRST_BASIC_INFO_SUCCESS ="LOAD_FIRST_BASIC_INFO_SUCCESS";
